services:
  frontend:
    image: registry.git-ce.rwth-aachen.de/tuda-fsr/uas/ros-pkgs/auto_apms_studio:jazzy
    container_name: auto_apms_studio_frontend
    ports:
      - "5173:5173"
    environment:
      - AUTO_APMS_STUDIO_WEB_PORT=5173
      - AUTO_APMS_STUDIO_WEB_HOST=0.0.0.0
    command: ros2 run auto_apms_studio start_web

  backend:
    image: registry.git-ce.rwth-aachen.de/tuda-fsr/uas/ros-pkgs/auto_apms_studio:jazzy
    container_name: auto_apms_studio_backend
    ports:
      - "3001:3001"
    environment:
      - AUTO_APMS_STUDIO_BACKEND_PORT=3001
      - AUTO_APMS_STUDIO_BACKEND_HOST=0.0.0.0
    command: ros2 run auto_apms_studio start_backend
