server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /auto_apms_studio/ {
        try_files $uri $uri/ /auto_apms_studio/index.html;
    }

    location = / {
        return 301 /auto_apms_studio/;
    }
}
